### ISSUE TITLE
DartanaMixin auto import not working

### ISSUE THREAD

**Issue by 0xPixelfrost** [matthiasbruns/dartana#3]
The DartanaMixin can not be resolved by the auto import function.

**Comment by 0xPixelfrost** [comment]
Solution suggestion: 
Rename the mixin or wait for a bugfix for
https://github.com/flutter/flutter-intellij/issues/3204

**Comment by matthiasbruns** [comment]
Same issue in VSCode

**Comment by 0xPixelfrost** [comment]
Issue timed out :D
